spring:
  datasource:
    jdbc-url: jdbc:h2:mem:menshiy_evgeniy
    username: SA
    password: password
    pool-size: 30
    set-connection-timeout: 1000
  thymeleaf:
    cache: false
  flyway:
    enabled: true
    baseline-on-migrate: true
